#!/usr/bin/env bash
#
# SEO verification smoke test for Mama Parichay (Nuxt SEO suite).
#
# Boots the production build locally and asserts every SEO surface renders:
# robots.txt, multilingual sitemap + hreflang, meta/OG/Twitter tags, canonical,
# in-head hreflang, JSON-LD, localized routes, and the dynamic OG image.
#
# Usage:
#   scripts/seo/verify.sh                 # build if needed, boot server, check
#   BUILD=1 scripts/seo/verify.sh         # force a fresh build first
#   PORT=4000 scripts/seo/verify.sh       # use a different local port
#   BASE_URL=https://foo.vercel.app scripts/seo/verify.sh
#                                         # check a remote URL (no build/boot)
#
# Exit code = number of failed checks (0 = all green).

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

PORT="${PORT:-3123}"
LOCALES=(en-IN hi-IN te-IN ta-IN mr-IN kn-IN)
SERVER_PID=""

# ── pretty output ────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
   G=$'\e[32m'; R=$'\e[31m'; Y=$'\e[33m'; C=$'\e[36m'; D=$'\e[2m'; B=$'\e[1m'; X=$'\e[0m'
else
   G=""; R=""; Y=""; C=""; D=""; B=""; X=""
fi
PASS=0; FAIL=0

pass()    { printf "  ${G}✔${X} %s\n" "$1"; PASS=$((PASS + 1)); }
fail()    { printf "  ${R}✗${X} %s${D} — %s${X}\n" "$1" "$2"; FAIL=$((FAIL + 1)); }
section() { printf "\n${B}%s${X}\n" "$1"; }

# assert_contains "<desc>" "<content>" "<regex>"
assert_contains() {
   if grep -qiE -- "$3" <<<"$2"; then pass "$1"; else fail "$1" "missing: $3"; fi
}

# ── server lifecycle ─────────────────────────────────────────────────────────
cleanup() {
   [[ -n "$SERVER_PID" ]] && kill "$SERVER_PID" 2>/dev/null
}
trap cleanup EXIT INT TERM

if [[ -n "${BASE_URL:-}" ]]; then
   BASE="${BASE_URL%/}"
   section "Target: ${C}${BASE}${X} ${D}(remote — no build/boot)${X}"
else
   BASE="http://localhost:${PORT}"
   if [[ "${BUILD:-0}" == "1" || ! -f .output/server/index.mjs ]]; then
      printf "${D}Building production output…${X}\n"
      if ! bun run build >/tmp/seo-build.log 2>&1; then
         printf "${R}Build failed.${X} See /tmp/seo-build.log\n"; tail -20 /tmp/seo-build.log; exit 1
      fi
   fi
   printf "${D}Starting server on :%s …${X}\n" "$PORT"
   PORT="$PORT" bun run .output/server/index.mjs >/tmp/seo-server.log 2>&1 &
   SERVER_PID=$!
   ready=0
   for _ in $(seq 1 30); do
      if curl -sf -o /dev/null "$BASE/"; then ready=1; break; fi
      sleep 1
   done
   if [[ "$ready" != "1" ]]; then
      printf "${R}Server never became ready.${X} See /tmp/seo-server.log\n"; tail -20 /tmp/seo-server.log; exit 1
   fi
   section "Target: ${C}${BASE}${X}"
fi

# ── fetch once, reuse ────────────────────────────────────────────────────────
HOME_HTML="$(curl -s "$BASE/")"
HI_HTML="$(curl -s "$BASE/hi")"
ROBOTS="$(curl -s "$BASE/robots.txt")"
SITEMAP_INDEX="$(curl -s "$BASE/sitemap_index.xml")"
SITEMAP_EN="$(curl -s "$BASE/__sitemap__/en-IN.xml")"

# ── robots ───────────────────────────────────────────────────────────────────
section "robots.txt"
assert_contains "generated by nuxt-robots" "$ROBOTS" "nuxt-robots"
assert_contains "references the sitemap"   "$ROBOTS" "Sitemap: https?://"
assert_contains "site is indexable"        "$ROBOTS" "User-agent: \*"

# ── sitemap ──────────────────────────────────────────────────────────────────
section "sitemap"
assert_contains "sitemap index served" "$SITEMAP_INDEX" "<sitemapindex"
for loc in "${LOCALES[@]}"; do
   assert_contains "index lists ${loc}" "$SITEMAP_INDEX" "__sitemap__/${loc}\.xml"
done
assert_contains "en-IN sitemap has hreflang alternates" "$SITEMAP_EN" "xhtml:link rel=\"alternate\""
assert_contains "en-IN sitemap has x-default"            "$SITEMAP_EN" "hreflang=\"x-default\""

# ── head meta (home) ─────────────────────────────────────────────────────────
section "meta tags (/)"
assert_contains "has <title>"            "$HOME_HTML" "<title>[^<]+</title>"
assert_contains "meta description"       "$HOME_HTML" "name=\"description\" content=\"[^\"]+\""
assert_contains "canonical URL"          "$HOME_HTML" "rel=\"canonical\""
assert_contains "og:title"               "$HOME_HTML" "property=\"og:title\""
assert_contains "og:image"               "$HOME_HTML" "property=\"og:image\""
assert_contains "twitter summary card"   "$HOME_HTML" "name=\"twitter:card\" content=\"summary_large_image\""

# ── in-head hreflang ─────────────────────────────────────────────────────────
section "hreflang (in <head>)"
assert_contains "x-default alternate"    "$HOME_HTML" "hreflang=\"x-default\""
assert_contains "hi-IN alternate"        "$HOME_HTML" "hreflang=\"hi-IN\""
assert_contains "hreflang URLs absolute" "$HOME_HTML" "href=\"https://[^\"]+\"[^>]*hreflang="

# ── structured data ──────────────────────────────────────────────────────────
section "structured data (JSON-LD)"
assert_contains "schema.org script present" "$HOME_HTML" "application/ld\+json"
assert_contains "graph declares @context"   "$HOME_HTML" "schema.org"

# ── localization ─────────────────────────────────────────────────────────────
section "localization (/hi)"
assert_contains "html lang is hi-IN"      "$HI_HTML" "<html[^>]*lang=\"hi-IN\""
assert_contains "title is translated"     "$HI_HTML" "बायोडाटा"

# ── dynamic OG image ─────────────────────────────────────────────────────────
section "OG image render"
OG_PATH="$(grep -oiE 'property="og:image" content="[^"]*"' <<<"$HOME_HTML" \
   | sed -E 's/.*content="([^"]*)".*/\1/' | sed -E 's#^https?://[^/]+##')"
if [[ -z "$OG_PATH" ]]; then
   fail "og:image URL found" "no og:image meta tag"
else
   read -r OG_CODE OG_TYPE OG_SIZE < <(curl -s -o /dev/null -w "%{http_code} %{content_type} %{size_download}" "$BASE$OG_PATH")
   if [[ "$OG_CODE" == "200" && "$OG_TYPE" == image/png* && "${OG_SIZE:-0}" -gt 1000 ]]; then
      pass "renders PNG (${OG_SIZE} bytes)"
   else
      fail "renders PNG" "code=$OG_CODE type=$OG_TYPE size=${OG_SIZE:-0}"
   fi
fi

# ── profile pages ────────────────────────────────────────────────────────────
# Every biodata is checked, not a sampled one: the slugs come from the data
# file itself (commented-out records start with `//`, so they are skipped),
# which means adding a profile automatically widens this run.
section "profile pages"
SLUGS="$(grep -oE '^[[:space:]]*slug: "[^"]+"' app/data/profiles.ts \
   | sed -E 's/.*slug: "([^"]+)".*/\1/')"

if [[ -z "$SLUGS" ]]; then
   fail "profiles found in app/data/profiles.ts" "no uncommented slug: entries"
fi

for slug in $SLUGS; do
   printf "\n  ${C}/%s${X}\n" "$slug"
   HTML="$(curl -s "$BASE/$slug")"

   assert_contains "has <title>"        "$HTML" "<title>[^<]+</title>"
   assert_contains "meta description"   "$HTML" "name=\"description\" content=\"[^\"]{20,}\""
   assert_contains "canonical is self"  "$HTML" "rel=\"canonical\" href=\"https?://[^\"]*/${slug}\""
   assert_contains "og:title"           "$HTML" "property=\"og:title\""
   assert_contains "og:type article"    "$HTML" "property=\"og:type\" content=\"article\""
   assert_contains "Person JSON-LD"     "$HTML" "\"@type\": ?\"Person\""
   assert_contains "hreflang alternates" "$HTML" "hreflang=\"te-IN\""
   assert_contains "listed in sitemap"  "$SITEMAP_EN" "<loc>[^<]*/${slug}</loc>"
   assert_contains "photos in sitemap"  "$SITEMAP_EN" "image:image"

   # The per-profile OG card must actually render, not just be linked.
   PROFILE_OG="$(grep -oiE 'property="og:image" content="[^"]*"' <<<"$HTML" \
      | sed -E 's/.*content="([^"]*)".*/\1/' | sed -E 's#^https?://[^/]+##' | head -1)"
   if [[ -z "$PROFILE_OG" ]]; then
      fail "og:image URL found" "no og:image meta tag"
   else
      read -r CODE TYPE SIZE < <(curl -s -o /dev/null -w "%{http_code} %{content_type} %{size_download}" "$BASE$PROFILE_OG")
      if [[ "$CODE" == "200" && "$TYPE" == image/png* && "${SIZE:-0}" -gt 1000 ]]; then
         pass "OG card renders PNG (${SIZE} bytes)"
      else
         fail "OG card renders PNG" "code=$CODE type=$TYPE size=${SIZE:-0}"
      fi
   fi

   # Localized variants must differ from the English page, or the six
   # hreflang alternates are duplicate content.
   TE_HTML="$(curl -s "$BASE/te/$slug")"
   assert_contains "/te html lang"      "$TE_HTML" "<html[^>]*lang=\"te-IN\""
   assert_contains "/te labels localized" "$TE_HTML" "వ్యక్తిగత సమాచారం"
   # "నుండి" ("from") sits early in the Telugu template, so this holds even
   # when a long role pushes the tail of the sentence past the 155-char clip.
   assert_contains "/te meta localized"  "$TE_HTML" "name=\"description\" content=\"[^\"]*నుండి"
done

# ── summary ──────────────────────────────────────────────────────────────────
printf "\n${B}Summary${X}  ${G}%d passed${X}  ${R}%d failed${X}\n" "$PASS" "$FAIL"
exit "$FAIL"
